spring:
  application:
    name: core.auth.sparqlite.com
  triplestore:
    driverClassName: virtuoso.jdbc4.Driver
    url: jdbc:virtuoso://virtuoso.server.hostname:1111
    username: dba
server:
  port: 80
mail:
  address:
    from: support@sparqlite.com
    admin: admin@sparqlite.com
  subject:
    newRegistration: Your registration to the site
    notifyRegistration: NEW registration:>
  body:
    newRegistration: newRegistration.vm
    notifyRegistration: notifyRegistration.vm
---
spring:
  profiles: development
logging:
  file: admin.log
  path: /tmp/coreauth/
